### ISSUE TITLE
Request to update endpoint names in RC User Guide

### ISSUE THREAD

**Issue by masonmq** [PSU-ICDS/icds_docs#72]
The latest endpoint names for RC and RR are `Penn State ICDS RC` and `Penn State ICDS Archive` with one space in between. I suggest updating the corresponding information in the #file-transfers section of our RC User Guide.

https://icds-docs.readthedocs.io/en/latest/04_HandlingData/#file-transfers

**Comment by ecetter** [comment]
fixed in pull request #73
